language: dart
branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "amfy"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - pub run test -r expanded
