language: dart

dart:
  - 2.5.1
  - stable
  
branches:
  only:
    - master

env:
  - DARTANALYZER_FLAGS=--fatal-warnings

install:
  - gem install coveralls-lcov

script: ./travis.sh
  
after_success:
  - coveralls-lcov --repo-token $COVERALLS_TOKEN var/lcov.info
  
cache:
  directories:
  - $HOME/.pub-cache
